---
title: "Campaign Events Analysis"
author: "Morgan Miller"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(plotly)

events <- readRDS("events_saved.rds")

events

```

## Intro

```{r}
##states most visited by each

Kamala_states <- filter(events, cand_lastname == "Harris")%>%
    count(state)

Bernie_states <- filter(events, cand_lastname == "Sanders")%>%
    count(state)

Biden_states <- filter(events, cand_lastname == "Biden")%>%
    count(state)

##cities most visited by each

Biden_cities <- filter(events, cand_lastname == "Biden")%>%
    count(city)

Bernie_cities <- filter(events, cand_lastname == "Sanders")%>%
    count(city)
  
Kamala_cities <- filter(events, cand_lastname == "Harris")%>%
    count(city)

##popular months for events by candidates

events_month <- events%>%
  mutate(month(date))
  
Kamala_months <- events_month%>%
  filter(cand_lastname == "Harris")%>%
  count(month = month(date))

Biden_months <- events_month%>%
  filter(cand_lastname == "Biden")%>%
  count(month = month(date))

Sanders_months <- events_month%>%
  filter(cand_lastname == "Sanders")%>%
  count(month = month(date))

##Charts based on months

Harris_Chart <- Kamala_months%>%
  plot_ly(x = ~month,
          y = ~n, 
          type = "bar")

harris_graph <- Harris_Chart%>%
  layout(title = "Visits for Harris per Month")

Biden_Chart <- Biden_months%>%
  plot_ly(x = ~month,
          y = ~n, 
          type = "bar")

biden_graph <- Biden_Chart%>%
  layout(title = "Visits for Biden per Month")

Sanders_Chart <- Sanders_months%>%
  plot_ly(x = ~month,
          y = ~n, 
          type = "bar")

sanders_graph <- Sanders_Chart%>%
  layout(title = "Visits for Sanders per Month")

Harris_Chart
Biden_Chart
Sanders_Chart

harris_graph

```

